### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by bertinatto** [flathub/org.gnome.Polari#2]
I'm using this flatpak without GNOME installed and I noticed that I don't get any notifications.

I suspect this something that I could configure in the Control Center. Or perhaps there's something missing in the metadata file?

Thanks!

**Comment by fmuellner** [comment]
What exactly did you test? Polari only emits notifications when someone mentions your nick in a public room, not for any messages in private conversations.

That is, this is likely not a packaging issue, but an [existing bug](https://gitlab.gnome.org/GNOME/polari/issues/18).

**Comment by bertinatto** [comment]
That was exactly my case!

Thanks for the info. I'll wait for the fix.
